### PR TITLE
Connect to 2.4 Ghz channels above 11

### PR DESCRIPTION
**Pull request by tmihai20**
This little modification will allow the tablet to connect to access points on channels over 11. I tested it extensively on MarshMallow and now on Nougat Roms.

### CODE REVIEW

**Comment by fefifofum** [comment]
This shouldn't make any difference, we don't use CRDA. Check this:
https://github.com/awifi-dev/android_kernel_lge_awifi/commit/3e3e2df21504194bb3be28a3e804d9e1ef7773ef
https://github.com/awifi-dev/android_kernel_lge_awifi/blob/cm-14.0/net/wireless/Kconfig#L97

**Comment by tmihai20** [comment]
I checked the same modification on AdrianoMartins AOSP as well. If I do not manually modify this ini, my V500 won't see any WiFi networks operating on channels above 11. I had the issue on MarshMallow based roms and I still have it on Nougat roms. build.prop must also be modified to include:

ro.wifi.channels=14

**Comment by fefifofum** [comment]
This repo if for my builds of cyanogenmod, not for adriano's aosp. I don't know what bugs his builds have, but in my builds I can connect to wifi networks on channels above 11 without needing this. So maybe this pull request is in the wrong repo...

**Comment by tmihai20** [comment]
I looked at your build first to see if there are any differences related to this file. If everything is ok, then I am closing my pull request.

**Pull request closed without merging**
